FROM teamide/build:1.3

EXPOSE 21080/tcp

COPY ../release/teamide-server-amd64/teamide /opt/teamide/teamide
COPY ../release/teamide-server-amd64/statics /opt/teamide/statics
COPY ../release/teamide-server-amd64/conf /opt/teamide/conf
COPY ../release/teamide-server-amd64/lib /opt/teamide/lib
COPY ../docker/docker-entrypoint.sh /opt/teamide/docker-entrypoint.sh
COPY ../docker/server.sh /opt/teamide/server.sh

ENV LD_LIBRARY_PATH=/opt/teamide/lib:$LD_LIBRARY_PATH
RUN chmod +x /opt/teamide/server.sh
RUN chmod +x /opt/teamide/docker-entrypoint.sh

WORKDIR /opt/teamide

CMD ["/opt/teamide/docker-entrypoint.sh"]


# cd html
# install
# npm run build
# go test -v -timeout 3600s -run ^TestStatic$ teamide/internal/static
# go build -ldflags "-s -X main.buildFlags=--isServer -X teamide/pkg/base.version=1.8.9" .