package wbsService

var (
	TABLE_WBS           = "TM_WBS"
	TABLE_USER_ACCOUNT  = "TM_USER_ACCOUNT"
	TABLE_USER_PASSWORD = "TM_USER_PASSWORD"
	TABLE_USER_METADATA = "TM_USER_METADATA"
	TABLE_USER_AUTH     = "TM_USER_AUTH"
	TABLE_USER_LOCK     = "TM_USER_LOCK"
	TABLE_USER_SETTING  = "TM_USER_SETTING"
)

type WbsService struct {
}
