package db

var (
	TABLE_INSTALL = "TM_INSTALL"

	TABLE_ID = "TM_ID"

	TABLE_USER          = "TM_USER"
	TABLE_USER_ACCOUNT  = "TM_USER_ACCOUNT"
	TABLE_USER_PASSWORD = "TM_USER_PASSWORD"
	TABLE_USER_METADATA = "TM_USER_METADATA"

	TABLE_SPACE = "TM_SPACE"
)
